services:
  samowarium:
    build: .
    image: vzalygin/samowarium:${DOCKER_TAG:-latest}
    working_dir: /samowarium
    env_file:
      - .env
    volumes:
      - db:/samowarium/db:rw
      - logs:/samowarium/logs:rw
    entrypoint:
      - python3
    command:
      - samowarium.py
    restart: unless-stopped
    ports:
      - 53000:53000

volumes:
  db:
  logs:
