services:
  samowarium:
    build: .
    image: vzalygin/samowarium:${DOCKER_TAG}
    working_dir: /samowarium
    env_file:
      - .env
    volumes:
      - db:/samowarium/db:rw
    entrypoint:
      - python3
    command:
      - samowarium.py

volumes:
  db:
