services:
  samowarium-prod:
    build: .
    image: vzalygin/samowarium:prod
    working_dir: /samowarium
    volumes:
      - prod-db:/samowarium/db:rw
    entrypoint:
      - python3
    command:
      - samowarium.py

  samowarium-dev:
    build: .
    image: vzalygin/samowarium:dev
    working_dir: /samowarium
    volumes:
      - dev-db:/samowarium/db:rw
    entrypoint:
      - python3
    command:
      - samowarium.py

volumes:
  prod-db:
    name: "samowarium-prod-db"
  dev-db:
    name: "samowarium-dev-db"
