#!/usr/local/bin/python3

from database import Database
from const import DB_PATH

with Database(DB_PATH) as db:
    db.initialize()

    clients = db.get_all_clients()

    print(len(clients), "users")
    print("telegram_id\tsamoware_id")
    for client in clients:
        telegram_id = client[0]
        samoware_id = client[1].samoware_login
        print(str(telegram_id)+"\t"+samoware_id)