# timeouts
HTTP_COMMON_TIMEOUT_SEC = 5
HTTP_CONENCT_LONGPOLL_TIMEOUT_SEC = 25
HTTP_TOTAL_LONGPOLL_TIMEOUT_SEC = 60
LONGPOLL_RETRY_DELAY_SEC = 10
HTTP_FILE_LOAD_TIMEOUT_SEC = 30

# tg message formats
HTML_FORMAT = "html"
MARKDOWN_FORMAT = "markdown"
