name: Deploy to development stand

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to checkout'
        required: false
      debug-logs:
        description: 'Enable DEBUG level logs'
        type: boolean
        default: false

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout specific commit
      if: ${{ inputs.commit != '' }}
      run:	git checkout ${{ inputs.commit }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Cache image
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: vzalygin/samowarium:dev

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Checkout specific commit
      if: ${{ inputs.commit != '' }}
      run:	git checkout ${{ inputs.commit }}

    - name: Prepare configuration
      run: |
        echo ENV=DEV >> .env;
        echo TELEGRAM_TOKEN=${{ secrets.DEV_TG_TOKEN }} >> .env;
        echo ENCRYPTION='${{ secrets.DEV_ENCRYPTION }}' >> .env;
        echo VERSION=$(git rev-parse --short HEAD) >> .env;

    - name: Enable DEBUG logs
      if: ${{ inputs.debug-logs }}
      run: |
        echo DEBUG= >> .env;

    - name: Configure Docker Host
      uses: khaledez/configure-docker-host@v2
      with:
        host: ${{ secrets.DEV_HOST }}
        user: ${{ secrets.DEV_SSH_USER }}
        ssh-private-key: ${{ secrets.DEV_SSH_KEY }}

    - name: Pull image
      run: |
          DOCKER_TAG=dev docker compose pull samowarium || 
          exit 1

    - name: Reload container
      run: |
          DOCKER_TAG=dev docker compose -p samowarium-dev down samowarium && 
          DOCKER_TAG=dev docker compose -p samowarium-dev up -d samowarium ||
          exit 1
