name: Deploy to development stage

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to checkout'
        required: false

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
   
    - name: Checkout specific commit
      if: ${{ inputs.commit != '' }}
      run:	git checkout ${{ inputs.commit }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Cache image
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: vzalygin/samowarium:dev

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
    - name: prepare configuration
      run: |
        ENV=DEV
        TELEGRAM_TOKEN=${{ secrets.DEV_TG_TOKEN }}

    - name: Configure Docker Host
      uses: khaledez/configure-docker-host@v2
      with:
        host: ${{ secrets.DEV_HOST }}
        user: ${{ secrets.DEV_SSH_USER }}
        ssh-private-key: ${{ secrets.DEV_SSH_KEY }}

    - name: Pull image
      run: |
          docker compose -f ../docker-compose.yml pull samowarium-dev

    - name: Reload container
      run: |
          docker compose down -f ../docker-compose.yml samowarium-dev && 
          docker compose up -d -f ../docker-compose.yml samowarium-dev
