name: Deploy to production

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to checkout'
        required: true
        default: 'main'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
   
    - name: checkout specific commit commit
      run:	git checkout ${{ inputs.commit }}

    - name: login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: vzalygin/samowarium:prod

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
    - name: prepare configuration
      run: |
        echo "ENV=PROD" > .env
        echo "TELEGRAM_TOKEN=${{ secrets.PROD_TG_TOKEN }}" > .env

    - name: copy env to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_SSH_USER }}
        ssh_private_key: ${{ secrets.PROD_SSH_KEY }} 
        local_path: './.env'
        remote_path: '~/.env'

    - name: copy configuration to server
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_SSH_USER }}
        ssh_private_key: ${{ secrets.PROD_SSH_KEY }} 
        local_path: './docker-compose.yml'
        remote_path: '~/docker-compose.yml'
    
    - name: pull image
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_SSH_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          docker compose pull samowarium-prod

    - name: reload container
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_SSH_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          docker compose down samowarium-prod && 
          docker compose up -d samowarium-prod

    - name: clean up
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_SSH_USER }}
        key: ${{ secrets.PROD_SSH_KEY }}
        script: |
          rm .env; 
          rm docker-compose.yml
